# Generated by Django 5.1.7 on 2025-03-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='watches',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
